min_version = "4.0"
env_list = ["py3.10", "py3.11", "py3.12", "py3.13", "py3.14"]

[env_run_base]
description = "run tests on {base_python}"
deps = ["-r requirements.txt", "--no-deps"]
commands = [["coverage", "run", "-m", "pytest", "--no-cov"]]

[env.compile]
description = "compile dependencies"
skip_install = true
deps = ["pip-tools"]
commands = [["pip-compile", "--no-emit-index-url", "--strip-extras", "--unsafe-package", "pip", { replace = "posargs", extend = true }]]
base_python = "3.10"
